### PR TITLE
test: prepare plugin for fastify 4.x

### PR DESCRIPTION
**Pull request by darkgl0w**
Hello.
This PR aims to :
- Replace `preParsing` hooks with `onRequest` hooks inside tests (https://github.com/fastify/fastify/issues/3503)
- Rewrite all tests (replacing Node.js `http.get` calls with `fastify.inject`, `async/await` ... )
- Add Node.js 17 to the CI matrix
- Fix windows flacky tests (maybe ... I hope at least :crossed_fingers: :smile_cat:)

#### Checklist

- [x] run `npm run test` ~~and `npm run benchmark`~~
- [x] tests ~~and/or benchmarks~~ are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by darkgl0w** [comment]
Hmmmm GitHub CI Windows runners failure 🤔 
Should not be related to the PR IMO: cf. [this commit CI run](https://github.com/darkgl0w/fastify-caching/actions/runs/1538546193)

**Comment by mcollina** [comment]
CI is failing :(

**Comment by darkgl0w** [comment]
> CI is failing :(

Can you manually trigger a CI re-run please ?
I expect this to be a problem on GitHub CI Windows runner side, If it fails again I will try to see what is triggering this issue ^^

**Comment by darkgl0w** [comment]
It seems that there is a flacky test when running in the Windows environment.
cf. https://github.com/fastify/fastify-caching/runs/4376801490?check_suite_focus=true and https://github.com/fastify/fastify-caching/runs/4376801490?check_suite_focus=true :thinking: 

I need to go, but I will try to look at this later today or tomorrow.

**Comment by darkgl0w** [comment]
OK it seems good now (I hope :smile_cat:), I ended up rewriting the tests (I swapped `http.get` calls with `fastify.inject` and I have gone `async/await` syntax), let me know if I need to change or revert anything. :stuck_out_tongue:

I have triggered a few CI run cycles and it seems to be OK so :crossed_fingers:.
For reference https://github.com/darkgl0w/fastify-caching/actions

**Review by jsumners — APPROVED** [review]
Looks good to me.

**Review by Eomm — APPROVED** [review]

**Comment by Eomm** [comment]
@darkgl0w the merge into master has some issue 😞 

> # test count(2) != plan(3)

https://github.com/fastify/fastify-caching/actions/runs/1541922678

Could you take a look?

**Comment by darkgl0w** [comment]
@Eomm > It seems that the root cause of the test flackyness is still there in Windows environments.
I will take a look tomorrow morning.

**Pull request merged**
