### PR TITLE
Moving towards 100% coverage #60

### PR DESCRIPTION
**Pull request by anthonyringoet**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

```
-----------|---------|----------|---------|---------|-------------------
File       | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
-----------|---------|----------|---------|---------|-------------------
All files  |      98 |    93.33 |     100 |   97.78 |
 plugin.js |      98 |    93.33 |     100 |   97.78 | 58
-----------|---------|----------|---------|---------|-------------------
```

The [only uncovered line 58](https://github.com/fastify/fastify-caching/blob/a7082639e5652742bee7d6a8526978a51ec82551/plugin.js#L58) does not seem to be reachable. If this is a function, it will be evaluated at the time the plugin is registered while giving access to the Fastify instance. The plugin receives the return value instead of the original function. I might be missing something though :)

https://www.fastify.io/docs/latest/Plugins/#plugin-options

### CODE REVIEW

**Comment by climba03003** [comment]
It should be reachable by doing this.
```js
fastify.register(plugin, function() {
  return function() {} // note that we return a function here and which will be passed toward the plugin.
})
```

**Comment by zekth** [comment]
Once 100% reached could you please delete the .taprc because we can get rid of this : https://github.com/fastify/fastify-caching/blob/master/.taprc#L1

**Comment by anthonyringoet** [comment]
Thanks for the feedback!

**Review by mcollina — APPROVED** [review]
lgtm

**Review by mcollina — APPROVED** [review]
lgtm

**Review by climba03003 — APPROVED** [review]
LGTM.

**Pull request merged**
