### PR TITLE
fix: typings of fastify.cache.get

### LINKED ISSUE #132: cache::get returns void in typescript
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.23.2

### Plugin version

8.3.0

### Node.js version

18.0.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

22.04

### Description

When using local cache (e.g. `fastify.cache.set` and `fastify.cache.get`), `fastify.cache.get` returns void by typescript definition.

### Steps to Reproduce

Use typescript and run `const res = await fastify.cache.get('something')`

res is void according to typescript and will result in compile error.

### Expected Behavior

_No response_

### PR DESCRIPTION
**Pull request by Uzlopak**
Resolves #132 

Question is, if a non callback `.get()` is returning a promise. 
I also assumed that if the key has no value it returns undefined.

Before merging it would be good to clear this.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
Checked...
If key has no value fastify.cache.get will return null
If useAwait for abstractcache is set, we need to return a promise

**Comment by jsumners** [comment]
Is there a specific question you need my input on?

**Comment by Uzlopak** [comment]
No I tested it and set the types based on the return values 
Also sry, i forgot you dont want to review typescript related PRs.

**Review by gurgunday — APPROVED** [review]
looks good to me

**Pull request merged**
